Repository brain-tec/partner-contact, pull requests merged in 2020-08, with the labels that each got.

#466 Syncing from upstream OCA/partner-contact (13.0)
  partner_fax/__manifest__.py
  partner_fax/views/res_partner.xml
Labels: 13.0

#468 Syncing from upstream OCA/partner-contact (13.0)
  base_location_geonames_import/i18n/pt_BR.po
  partner_bank_active/i18n/pt_BR.po
  partner_coc/i18n/pt_BR.po
  partner_contact_birthdate/i18n/pt_BR.po
  partner_contact_gender/i18n/pt_BR.po
  partner_contact_lang/i18n/pt_BR.po
  partner_deduplicate_by_ref/i18n/pt_BR.po
  partner_disable_gravatar/i18n/pt_BR.po
Labels: 13.0

#470 Syncing from upstream OCA/partner-contact (12.0)
  base_location/__manifest__.py
  base_location/models/res_partner.py
Labels: 12.0

#471 Syncing from upstream OCA/partner-contact (8.0)
  base_partner_merge/i18n/de.po
  base_partner_merge/i18n/es.po
  base_partner_merge/i18n/eu.po
  base_partner_merge/i18n/pt_BR.po
  base_partner_merge/i18n/sl.po
Labels: 8.0

#472 Syncing from upstream OCA/partner-contact (10.0)
  partner_alias/i18n/cs_CZ.po
  partner_alias/i18n/da.po
  partner_alias/i18n/de.po
  partner_alias/i18n/es.po
  partner_alias/i18n/fr.po
  partner_alias/i18n/hr.po
  partner_alias/i18n/hr_HR.po
  partner_alias/i18n/it.po
  partner_alias/i18n/nl.po
  partner_alias/i18n/nl_NL.po
  partner_alias/i18n/pt_BR.po
  partner_alias/i18n/sl.po
  partner_contact_configuration/i18n/fr.po
Labels: 10.0

#474 Syncing from upstream OCA/partner-contact (13.0)
  base_location/i18n/da.po
  base_location/i18n/de.po
  base_location/i18n/es.po
  base_location/i18n/es_CO.po
  base_location/i18n/fr.po
  base_location/i18n/hr_HR.po
  base_location/i18n/it.po
  base_location/i18n/nl_NL.po
  base_location/i18n/pt_PT.po
  base_location/i18n/sl.po
  base_location_geonames_import/i18n/da.po
  base_location_geonames_import/i18n/de.po
  base_location_geonames_import/i18n/es.po
  base_location_geonames_import/i18n/fi.po
  base_location_geonames_import/i18n/fr.po
  base_location_geonames_import/i18n/hr_HR.po
  base_location_geonames_import/i18n/it.po
  base_location_geonames_import/i18n/nl.po
  base_location_geonames_import/i18n/nl_NL.po
  base_location_geonames_import/i18n/pt.po
  base_location_geonames_import/i18n/pt_PT.po
  base_location_geonames_import/i18n/sl.po
  base_location_nuts/i18n/de.po
  base_location_nuts/i18n/es.po
  base_location_nuts/i18n/fi.po
  base_location_nuts/i18n/fr.po
  base_location_nuts/i18n/pt.po
  base_location_nuts/i18n/pt_PT.po
  base_location_nuts/i18n/sl.po
  base_location_nuts/i18n/tr.po
  partner_industry_secondary/i18n/cs_CZ.po
  partner_industry_secondary/i18n/de.po
  partner_industry_secondary/i18n/fi.po
  partner_industry_secondary/i18n/fr.po
  partner_industry_secondary/i18n/pt.po
  partner_industry_secondary/i18n/pt_PT.po
  partner_industry_secondary/i18n/sl.po
  partner_industry_secondary/i18n/tr.po
  partner_label/i18n/cs_CZ.po
  partner_label/i18n/es.po
  partner_label/i18n/hr.po
  partner_label/i18n/hr_HR.po
  partner_label/i18n/nl_NL.po
Labels: 13.0

#475 Update 20200825 updating from braintec fork for version 13
  base_location/i18n/da.po
  base_location/i18n/de.po
  base_location/i18n/es.po
  base_location/i18n/es_CO.po
  base_location/i18n/fr.po
  base_location/i18n/hr_HR.po
  base_location/i18n/it.po
  base_location/i18n/nl_NL.po
  base_location/i18n/pt_PT.po
  base_location/i18n/sl.po
  base_location_geonames_import/i18n/da.po
  base_location_geonames_import/i18n/de.po
  base_location_geonames_import/i18n/es.po
  base_location_geonames_import/i18n/fi.po
  base_location_geonames_import/i18n/fr.po
  base_location_geonames_import/i18n/hr_HR.po
  base_location_geonames_import/i18n/it.po
  base_location_geonames_import/i18n/nl.po
  base_location_geonames_import/i18n/nl_NL.po
  base_location_geonames_import/i18n/pt.po
  base_location_geonames_import/i18n/pt_BR.po
  base_location_geonames_import/i18n/pt_PT.po
  base_location_geonames_import/i18n/sl.po
  base_location_nuts/i18n/de.po
  base_location_nuts/i18n/es.po
  base_location_nuts/i18n/fi.po
  base_location_nuts/i18n/fr.po
  base_location_nuts/i18n/pt.po
  base_location_nuts/i18n/pt_PT.po
  base_location_nuts/i18n/sl.po
  base_location_nuts/i18n/tr.po
  partner_bank_active/i18n/pt_BR.po
  partner_coc/i18n/pt_BR.po
  partner_contact_birthdate/i18n/pt_BR.po
  partner_contact_gender/i18n/pt_BR.po
  partner_contact_lang/i18n/pt_BR.po
  partner_deduplicate_by_ref/i18n/pt_BR.po
  partner_disable_gravatar/i18n/pt_BR.po
  partner_industry_secondary/i18n/cs_CZ.po
  partner_industry_secondary/i18n/de.po
  partner_industry_secondary/i18n/fi.po
  partner_industry_secondary/i18n/fr.po
  partner_industry_secondary/i18n/pt.po
  partner_industry_secondary/i18n/pt_PT.po
  partner_industry_secondary/i18n/sl.po
  partner_industry_secondary/i18n/tr.po
  partner_label/i18n/cs_CZ.po
  partner_label/i18n/es.po
  partner_label/i18n/hr.po
  partner_label/i18n/hr_HR.po
  partner_label/i18n/nl_NL.po
Labels: 13.0.project_mi_465
