Repository brain-tec/partner-contact, pull requests merged in 2021-11, with the labels that each got.

#633 Syncing from upstream OCA/partner-contact (11.0)
  partner_multi_name/.vscode/settings.json
  partner_multi_name/README.rst
  partner_multi_name/__init__.py
  partner_multi_name/__manifest__.py
  partner_multi_name/i18n/es CO.po
  partner_multi_name/i18n/es.po
  partner_multi_name/i18n/partner_multi_name.pot
  partner_multi_name/i18n/partner_other_names.pot
  partner_multi_name/models/__init__.py
  partner_multi_name/models/res_config_settings.py
  partner_multi_name/models/res_partner.py
  partner_multi_name/models/res_users.py
  partner_multi_name/static/description/icon.png
  partner_multi_name/views/res_partner_views.xml
  partner_multi_name/views/res_users_views.xml
  partner_tag_smart_assignation/__manifest__.py
  partner_tag_smart_assignation/models/res_partner_category.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/partner_multi_name/odoo/addons/partner_multi_name
  setup/partner_multi_name/setup.cfg
  setup/partner_multi_name/setup.py
Labels: 11.0

#637 Syncing from upstream OCA/partner-contact (14.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  CONTRIBUTING.md
  partner_contact_birthdate/i18n/pt.po
  partner_contact_gender/i18n/pt.po
  partner_contact_personal_information_page/i18n/pt.po
  partner_multi_relation/i18n/pt.po
Labels: 14.0

#638 Syncing from upstream OCA/partner-contact (15.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  CONTRIBUTING.md
Labels: 15.0

#640 [t125614][MIG] Removed attributes for name that were overwritting the core ones
  partner_firstname/views/res_partner.xml
Labels: 15.0.project_mi_465

#642 Fixing pre-commit errors partner_firstname
  partner_firstname/models/base_config_settings.py
  partner_firstname/models/res_partner.py
  partner_firstname/tests/test_create.py
  partner_firstname/tests/test_delete.py
  partner_firstname/tests/test_name.py
Labels: bug, 15.0.project_mi_465

#643 Fixing missing setup for partner_firstname
  setup/partner_firstname/odoo/addons/partner_firstname
  setup/partner_firstname/setup.py
Labels: 15.0.project_mi_465

#644 Fixing issue with views as core ones have been changed having field n…
  partner_firstname/views/res_partner.xml
Labels: bug, 15.0.project_mi_465

#645 [t125614] Fixing issue with views in partner_firstname
  partner_firstname/views/res_partner.xml
Labels: bug, 15.0.project_mi_465

#646 Syncing from upstream OCA/partner-contact (12.0)
  README.md
  base_location/__manifest__.py
  base_location/models/res_partner.py
  base_location/tests/test_base_location.py
Labels: 12.0

#647 Syncing from upstream OCA/partner-contact (13.0)
  README.md
  base_location/__manifest__.py
  base_location/models/res_partner.py
  base_location/tests/test_base_location.py
Labels: 13.0

#648 Syncing from upstream OCA/partner-contact (12.0)
  README.md
  partner_company_group/__manifest__.py
  partner_company_group/i18n/ca.po
  partner_company_group/i18n/ca_ES.po
  partner_company_group/i18n/es.po
  partner_company_group/i18n/it.po
  partner_company_group/i18n/partner_company_group.pot
  partner_company_group/models/res_partner.py
  partner_company_group/tests/__init__.py
  partner_company_group/tests/test_partner_company_group.py
Labels: 12.0

#649 Syncing from upstream OCA/partner-contact (14.0)
  README.md
  partner_identification_gln/README.rst
  partner_identification_gln/__init__.py
  partner_identification_gln/__manifest__.py
  partner_identification_gln/data/partner_identification_gln.xml
  partner_identification_gln/i18n/partner_identification_gln.pot
  partner_identification_gln/i18n/sl.po
  partner_identification_gln/models/__init__.py
  partner_identification_gln/models/res_partner_id_category.py
  partner_identification_gln/readme/CONTRIBUTORS.rst
  partner_identification_gln/readme/DESCRIPTION.rst
  partner_identification_gln/readme/INSTALL.rst
  partner_identification_gln/static/description/icon.svg
  partner_identification_gln/static/description/index.html
  partner_identification_gln/tests/__init__.py
  partner_identification_gln/tests/test_gln.py
  requirements.txt
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/partner_identification_gln/odoo/addons/partner_identification_gln
  setup/partner_identification_gln/setup.py
Labels: 14.0

#651 Syncing from upstream OCA/partner-contact (14.0)
  README.md
  base_location/__manifest__.py
  base_location/models/res_partner.py
  partner_identification/i18n/pt_PT.po
Labels: 14.0

#652 Syncing from upstream OCA/partner-contact (15.0)
  README.md
  base_country_state_translatable/README.rst
  base_country_state_translatable/__init__.py
  base_country_state_translatable/__manifest__.py
  base_country_state_translatable/i18n/base_country_state_translatable.pot
  base_country_state_translatable/i18n/da.po
  base_country_state_translatable/i18n/de.po
  base_country_state_translatable/i18n/es.po
  base_country_state_translatable/i18n/fr.po
  base_country_state_translatable/i18n/hr.po
  base_country_state_translatable/i18n/hr_HR.po
  base_country_state_translatable/i18n/it.po
  base_country_state_translatable/i18n/pt_BR.po
  base_country_state_translatable/i18n/sl.po
  base_country_state_translatable/models/__init__.py
  base_country_state_translatable/models/res_country.py
  base_country_state_translatable/readme/CONTRIBUTORS.rst
  base_country_state_translatable/readme/DESCRIPTION.rst
  base_country_state_translatable/readme/USAGE.rst
  base_country_state_translatable/static/description/icon.png
  base_country_state_translatable/static/description/index.html
  base_location/__manifest__.py
  base_location/models/res_partner.py
  partner_fax/README.rst
  partner_fax/__init__.py
  partner_fax/__manifest__.py
  partner_fax/i18n/de.po
  partner_fax/i18n/es.po
  partner_fax/i18n/fr.po
  partner_fax/i18n/he.po
  partner_fax/i18n/hr_HR.po
  partner_fax/i18n/it.po
  partner_fax/i18n/nl.po
  partner_fax/i18n/partner_fax.pot
  partner_fax/i18n/pt_BR.po
  partner_fax/i18n/sl.po
  partner_fax/i18n/zh_CN.po
  partner_fax/models/__init__.py
  partner_fax/models/res_partner.py
  partner_fax/readme/CONTRIBUTORS.rst
  partner_fax/readme/DESCRIPTION.rst
  partner_fax/readme/USAGE.rst
  partner_fax/static/description/icon.png
  partner_fax/static/description/index.html
  partner_fax/views/res_partner.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/base_country_state_translatable/odoo/addons/base_country_state_translatable
  setup/base_country_state_translatable/setup.py
  setup/partner_fax/odoo/addons/partner_fax
  setup/partner_fax/setup.py
Labels: 15.0

#654 Syncing from upstream OCA/partner-contact (14.0)
  README.md
  partner_identification_notification/README.rst
  partner_identification_notification/__init__.py
  partner_identification_notification/__manifest__.py
  partner_identification_notification/data/ir_cron_data.xml
  partner_identification_notification/i18n/partner_identification_notification.pot
  partner_identification_notification/models/__init__.py
  partner_identification_notification/models/res_partner_id_category.py
  partner_identification_notification/models/res_partner_id_number.py
  partner_identification_notification/readme/CONTRIBUTORS.rst
  partner_identification_notification/readme/DESCRIPTION.rst
  partner_identification_notification/static/description/icon.png
  partner_identification_notification/static/description/index.html
  partner_identification_notification/views/res_partner_id_category_view.xml
  partner_identification_notification/views/res_partner_id_number_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/partner_identification_notification/odoo/addons/partner_identification_notification
  setup/partner_identification_notification/setup.py
Labels: 14.0
