Repository brain-tec/partner-contact, pull requests merged in 2022-05, with the labels that each got.

#747 Syncing from upstream OCA/partner-contact (14.0)
  README.md
  partner_tier_validation/__manifest__.py
  partner_tier_validation/models/res_partner.py
Labels: 14.0

#748 Syncing from upstream OCA/partner-contact (14.0)
  partner_contact_in_several_companies/i18n/it.po
Labels: 14.0

#751 Updating misalignement partner-firstname according to OCA 15.0
  partner_firstname/README.rst
  partner_firstname/__manifest__.py
  partner_firstname/hooks.py
  partner_firstname/models/res_partner.py
  partner_firstname/models/res_users.py
  partner_firstname/readme/CONTRIBUTORS.rst
  partner_firstname/static/description/index.html
  partner_firstname/tests/test_create.py
  partner_firstname/tests/test_delete.py
  partner_firstname/tests/test_name.py
  partner_firstname/tests/test_partner_form.py
  partner_firstname/views/base_config_view.xml
  partner_firstname/views/res_partner.xml
  partner_firstname/views/res_user.xml
Labels: 15.0.project_mi_465

#754 Syncing from upstream OCA/partner-contact (12.0)
  partner_pricelist_search/i18n/fr.po
Labels: 12.0

#755 Syncing from upstream OCA/partner-contact (14.0)
  README.md
  partner_contact_address_default/__manifest__.py
  partner_contact_address_default/models/res_partner.py
  partner_contact_address_default/tests/test_partner_contact_address_default.py
  partner_contact_address_default/views/res_partner_views.xml
Labels: 14.0

#756 Syncing from upstream OCA/partner-contact (14.0)
  partner_contact_birthdate/i18n/es.po
  partner_contact_birthplace/i18n/ca.po
  partner_contact_birthplace/i18n/es_ES.po
  partner_contact_lang/i18n/ca.po
  partner_contact_lang/i18n/es.po
  partner_phone_secondary/i18n/ca.po
Labels: 14.0

#757 Syncing from upstream OCA/partner-contact (14.0)
  README.md
  partner_firstname/__manifest__.py
  partner_firstname/i18n/am.po
  partner_firstname/i18n/ar.po
  partner_firstname/i18n/bg.po
  partner_firstname/i18n/bs.po
  partner_firstname/i18n/ca.po
  partner_firstname/i18n/cs.po
  partner_firstname/i18n/da.po
  partner_firstname/i18n/de.po
  partner_firstname/i18n/el_GR.po
  partner_firstname/i18n/en_GB.po
  partner_firstname/i18n/es.po
  partner_firstname/i18n/es_CR.po
  partner_firstname/i18n/es_EC.po
  partner_firstname/i18n/es_MX.po
  partner_firstname/i18n/es_VE.po
  partner_firstname/i18n/et.po
  partner_firstname/i18n/eu.po
  partner_firstname/i18n/fi.po
  partner_firstname/i18n/fr.po
  partner_firstname/i18n/fr_CA.po
  partner_firstname/i18n/fr_CH.po
  partner_firstname/i18n/gl.po
  partner_firstname/i18n/hr.po
  partner_firstname/i18n/hr_HR.po
  partner_firstname/i18n/hu.po
  partner_firstname/i18n/it.po
  partner_firstname/i18n/ja.po
  partner_firstname/i18n/lt.po
  partner_firstname/i18n/lv.po
  partner_firstname/i18n/mk.po
  partner_firstname/i18n/mn.po
  partner_firstname/i18n/nb.po
  partner_firstname/i18n/nb_NO.po
  partner_firstname/i18n/nl.po
  partner_firstname/i18n/nl_BE.po
  partner_firstname/i18n/nl_NL.po
  partner_firstname/i18n/partner_firstname.pot
  partner_firstname/i18n/pl.po
  partner_firstname/i18n/pt.po
  partner_firstname/i18n/pt_BR.po
  partner_firstname/i18n/pt_PT.po
  partner_firstname/i18n/ro.po
  partner_firstname/i18n/ru.po
  partner_firstname/i18n/sk.po
  partner_firstname/i18n/sl.po
  partner_firstname/i18n/sr@latin.po
  partner_firstname/i18n/sv.po
  partner_firstname/i18n/th.po
  partner_firstname/i18n/tr.po
  partner_firstname/i18n/tr_TR.po
  partner_firstname/i18n/vi.po
  partner_firstname/i18n/zh_CN.po
  partner_firstname/i18n/zh_TW.po
  partner_firstname/models/res_partner.py
  partner_firstname/tests/base.py
Labels: 14.0

#758 Syncing from upstream OCA/partner-contact (14.0)
  README.md
  partner_firstname/__manifest__.py
  partner_firstname/models/base_config_settings.py
  partner_second_lastname/__manifest__.py
  partner_second_lastname/tests/test_name.py
Labels: 14.0

#759 Syncing from upstream OCA/partner-contact (13.0)
  base_location/i18n/es_MX.po
Labels: 13.0

#760 Syncing from upstream OCA/partner-contact (15.0)
  README.md
  animal/i18n/animal.pot
  animal/i18n/ca.po
  animal/i18n/es.po
  partner_customer_supplier/README.rst
  partner_customer_supplier/__init__.py
  partner_customer_supplier/__manifest__.py
  partner_customer_supplier/i18n/partner_customer_supplier.pot
  partner_customer_supplier/models/__init__.py
  partner_customer_supplier/models/res_partner.py
  partner_customer_supplier/readme/CONTRIBUTORS.rst
  partner_customer_supplier/readme/CREDITS.rst
  partner_customer_supplier/readme/DESCRIPTION.rst
  partner_customer_supplier/static/description/icon.png
  partner_customer_supplier/static/description/index.html
  partner_customer_supplier/tests/__init__.py
  partner_customer_supplier/tests/test_res_partner.py
  partner_customer_supplier/views/res_partner_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/partner_customer_supplier/odoo/addons/partner_customer_supplier
  setup/partner_customer_supplier/setup.py
Labels: 15.0
