Repository brain-tec/partner-contact, pull requests merged in 2022-08, with the labels that each got.

#777 Syncing from upstream OCA/partner-contact (14.0)
  base_location/i18n/es.po
  partner_bank_code/i18n/fr.po
  partner_contact_lang/i18n/fr.po
  partner_employee_quantity/i18n/fr.po
  partner_vat_unique/i18n/fr.po
Labels: 14.0

#778 Syncing from upstream OCA/partner-contact (14.0)
  README.md
  partner_tz/README.rst
  partner_tz/__manifest__.py
  partner_tz/static/description/index.html
Labels: 14.0

#779 Syncing from upstream OCA/partner-contact (14.0)
  README.md
  partner_vat_unique/__manifest__.py
Labels: 14.0

#780 Syncing from upstream OCA/partner-contact (13.0)
  .copier-answers.yml
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .travis.yml
  README.md
  base_location_nuts/__manifest__.py
  partner_address_two_lines/__manifest__.py
  partner_coc/__manifest__.py
  partner_contact_gender/__manifest__.py
  partner_contact_lang/__manifest__.py
  partner_deduplicate_by_ref/__manifest__.py
  partner_label/__manifest__.py
  partner_phone_extension/__manifest__.py
  partner_pricelist_tracking/__manifest__.py
  partner_ref_unique/__manifest__.py
  portal_partner_data_no_edit/__manifest__.py
  portal_partner_select_all/__manifest__.py
Labels: 13.0

#781 Syncing from upstream OCA/partner-contact (14.0)
  partner_company_type/i18n/pt.po
  partner_phone_extension/i18n/pt.po
  partner_stage/i18n/pt.po
Labels: 14.0

#782 Syncing from upstream OCA/partner-contact (14.0)
  base_location/i18n/hr.po
  partner_address_street3/i18n/hr.po
  partner_affiliate/i18n/fr.po
  partner_bank_code/i18n/hr.po
  partner_contact_birthdate/i18n/hr.po
  partner_contact_gender/i18n/hr.po
  partner_firstname/i18n/hr.po
  partner_second_lastname/i18n/hr.po
Labels: 14.0

#783 Syncing from upstream OCA/partner-contact (15.0)
  README.md
  animal/i18n/animal.pot
  animal/i18n/ca.po
  animal/i18n/es.po
  partner_company_group/README.rst
  partner_company_group/__init__.py
  partner_company_group/__manifest__.py
  partner_company_group/hooks.py
  partner_company_group/i18n/ca.po
  partner_company_group/i18n/es.po
  partner_company_group/i18n/partner_company_group.pot
  partner_company_group/i18n/zh_CN.po
  partner_company_group/models/__init__.py
  partner_company_group/models/account_move.py
  partner_company_group/models/crm_lead.py
  partner_company_group/models/res_partner.py
  partner_company_group/models/sale_order.py
  partner_company_group/readme/CONTRIBUTORS.rst
  partner_company_group/readme/DESCRIPTION.rst
  partner_company_group/static/description/icon.png
  partner_company_group/static/description/index.html
  partner_company_group/tests/__init__.py
  partner_company_group/tests/test_partner_company_group.py
  partner_company_group/views/account_move_views.xml
  partner_company_group/views/contact_view.xml
  partner_company_group/views/opportunity_view.xml
  partner_company_group/views/sale_order_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/partner_company_group/odoo/addons/partner_company_group
  setup/partner_company_group/setup.py
Labels: 15.0

#784 Syncing from upstream OCA/partner-contact (14.0)
  README.md
  partner_category_security/README.rst
  partner_category_security/__init__.py
  partner_category_security/__manifest__.py
  partner_category_security/i18n/es.po
  partner_category_security/i18n/partner_category_security.pot
  partner_category_security/readme/CONTRIBUTORS.rst
  partner_category_security/readme/DESCRIPTION.rst
  partner_category_security/readme/USAGE.rst
  partner_category_security/security/ir.model.access.csv
  partner_category_security/security/security.xml
  partner_category_security/static/description/icon.png
  partner_category_security/static/description/index.html
  partner_category_security/tests/__init__.py
  partner_category_security/tests/test_partner_category_security.py
  partner_category_security/views/menu.xml
  partner_category_security/views/res_partner_view.xml
  partner_contact_lang/i18n/hr.po
  partner_firstname/i18n/hr.po
  partner_multi_relation/i18n/hr.po
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/partner_category_security/odoo/addons/partner_category_security
  setup/partner_category_security/setup.py
Labels: 14.0

#785 Syncing from upstream OCA/partner-contact (14.0)
  README.md
  partner_category_security_crm/README.rst
  partner_category_security_crm/__init__.py
  partner_category_security_crm/__manifest__.py
  partner_category_security_crm/i18n/es.po
  partner_category_security_crm/i18n/partner_category_security_crm.pot
  partner_category_security_crm/readme/CONTRIBUTORS.rst
  partner_category_security_crm/readme/DESCRIPTION.rst
  partner_category_security_crm/readme/USAGE.rst
  partner_category_security_crm/security/ir.model.access.csv
  partner_category_security_crm/static/description/icon.png
  partner_category_security_crm/static/description/index.html
  partner_category_security_crm/tests/__init__.py
  partner_category_security_crm/tests/test_partner_category_security_crm.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/partner_category_security_crm/odoo/addons/partner_category_security_crm
  setup/partner_category_security_crm/setup.py
Labels: 14.0

#786 Backmerging 15.0 into 15.0.project_MI_465
  README.md
  animal/i18n/animal.pot
  animal/i18n/ca.po
  animal/i18n/es.po
  partner_company_group/README.rst
  partner_company_group/__init__.py
  partner_company_group/__manifest__.py
  partner_company_group/hooks.py
  partner_company_group/i18n/ca.po
  partner_company_group/i18n/es.po
  partner_company_group/i18n/partner_company_group.pot
  partner_company_group/i18n/zh_CN.po
  partner_company_group/models/__init__.py
  partner_company_group/models/account_move.py
  partner_company_group/models/crm_lead.py
  partner_company_group/models/res_partner.py
  partner_company_group/models/sale_order.py
  partner_company_group/readme/CONTRIBUTORS.rst
  partner_company_group/readme/DESCRIPTION.rst
  partner_company_group/static/description/icon.png
  partner_company_group/static/description/index.html
  partner_company_group/tests/__init__.py
  partner_company_group/tests/test_partner_company_group.py
  partner_company_group/views/account_move_views.xml
  partner_company_group/views/contact_view.xml
  partner_company_group/views/opportunity_view.xml
  partner_company_group/views/sale_order_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/partner_company_group/odoo/addons/partner_company_group
  setup/partner_company_group/setup.py
Labels: 15.0.project_mi_465
