Repository brain-tec/partner-contact, pull requests merged in 2022-02, with the labels that each got.

#682 Syncing from upstream OCA/partner-contact (14.0)
  README.md
  animal_owner/__manifest__.py
  animal_owner/models/res_partner.py
  base_location/i18n/pt_BR.po
  partner_contact_address_default/i18n/fr.po
  partner_contact_address_default/i18n/fr_FR.po
  partner_contact_birthplace/README.rst
  partner_contact_birthplace/__init__.py
  partner_contact_birthplace/__manifest__.py
  partner_contact_birthplace/i18n/it.po
  partner_contact_birthplace/i18n/partner_contact_birthplace.pot
  partner_contact_birthplace/models/__init__.py
  partner_contact_birthplace/models/res_partner.py
  partner_contact_birthplace/static/description/icon.png
  partner_contact_birthplace/views/res_partner.xml
  partner_contact_in_several_companies/__manifest__.py
  partner_contact_in_several_companies/tests/test_partner_contact_in_several_companies.py
  partner_contact_nationality/i18n/pt_BR.po
  partner_helper/i18n/pt_BR.po
  partner_pricelist_search/__manifest__.py
  partner_pricelist_search/models/product_pricelist.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/partner_contact_birthplace/odoo/addons/partner_contact_birthplace
  setup/partner_contact_birthplace/setup.py
Labels: 14.0

#683 Syncing from upstream OCA/partner-contact (14.0)
  partner_contact_address_default/i18n/fr.po
  partner_contact_address_default/i18n/fr_FR.po
Labels: 14.0

#684 Syncing from upstream OCA/partner-contact (14.0)
  base_location/i18n/nl.po
Labels: 14.0

#687 Syncing from upstream OCA/partner-contact (14.0)
  README.md
  animal/__manifest__.py
  animal/i18n/animal.pot
  animal/i18n/es.po
  animal/i18n/fr.po
  animal/models/animal_breed.py
  animal/models/animal_species.py
  animal/security/ir.model.access.csv
  animal/views/animal_breed.xml
  animal/views/animal_species.xml
  animal_owner/__manifest__.py
  animal_owner/views/animal.xml
Labels: 14.0

#690 15.0.project 578 partner contact personal information page
  partner_contact_personal_information_page/README.rst
  partner_contact_personal_information_page/__init__.py
  partner_contact_personal_information_page/__manifest__.py
  partner_contact_personal_information_page/i18n/da.po
  partner_contact_personal_information_page/i18n/de.po
  partner_contact_personal_information_page/i18n/en.po
  partner_contact_personal_information_page/i18n/es.po
  partner_contact_personal_information_page/i18n/fi.po
  partner_contact_personal_information_page/i18n/fr.po
  partner_contact_personal_information_page/i18n/hr_HR.po
  partner_contact_personal_information_page/i18n/hu.po
  partner_contact_personal_information_page/i18n/it.po
  partner_contact_personal_information_page/i18n/nl.po
  partner_contact_personal_information_page/i18n/partner_contact_personal_information_page.pot
  partner_contact_personal_information_page/i18n/pt.po
  partner_contact_personal_information_page/i18n/pt_BR.po
  partner_contact_personal_information_page/i18n/pt_PT.po
  partner_contact_personal_information_page/i18n/sl.po
  partner_contact_personal_information_page/readme/CONTRIBUTORS.rst
  partner_contact_personal_information_page/readme/DESCRIPTION.rst
  partner_contact_personal_information_page/readme/USAGE.rst
  partner_contact_personal_information_page/static/description/icon.png
  partner_contact_personal_information_page/static/description/index.html
  partner_contact_personal_information_page/views/res_partner.xml
  setup/partner_contact_personal_information_page/odoo/addons/partner_contact_personal_information_page
  setup/partner_contact_personal_information_page/setup.py
Labels: 15.0.project_ge_578

#692 Syncing from upstream OCA/partner-contact (10.0)
  partner_firstname/i18n/fr.po
Labels: 10.0

#693 Syncing from upstream OCA/partner-contact (15.0)
  README.md
  partner_contact_personal_information_page/README.rst
  partner_contact_personal_information_page/__init__.py
  partner_contact_personal_information_page/__manifest__.py
  partner_contact_personal_information_page/i18n/da.po
  partner_contact_personal_information_page/i18n/de.po
  partner_contact_personal_information_page/i18n/en.po
  partner_contact_personal_information_page/i18n/es.po
  partner_contact_personal_information_page/i18n/fi.po
  partner_contact_personal_information_page/i18n/fr.po
  partner_contact_personal_information_page/i18n/hr_HR.po
  partner_contact_personal_information_page/i18n/hu.po
  partner_contact_personal_information_page/i18n/it.po
  partner_contact_personal_information_page/i18n/nl.po
  partner_contact_personal_information_page/i18n/partner_contact_personal_information_page.pot
  partner_contact_personal_information_page/i18n/pt.po
  partner_contact_personal_information_page/i18n/pt_BR.po
  partner_contact_personal_information_page/i18n/pt_PT.po
  partner_contact_personal_information_page/i18n/sl.po
  partner_contact_personal_information_page/readme/CONTRIBUTORS.rst
  partner_contact_personal_information_page/readme/DESCRIPTION.rst
  partner_contact_personal_information_page/readme/USAGE.rst
  partner_contact_personal_information_page/static/description/icon.png
  partner_contact_personal_information_page/static/description/index.html
  partner_contact_personal_information_page/views/res_partner.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/partner_contact_personal_information_page/odoo/addons/partner_contact_personal_information_page
  setup/partner_contact_personal_information_page/setup.py
Labels: 15.0

#694 Syncing from upstream OCA/partner-contact (13.0)
  README.md
  base_location/migrations/13.0.1.0.0/pre-migration.py
  partner_contact_address_default/__manifest__.py
  partner_contact_address_default/models/res_partner.py
  partner_contact_address_default/tests/test_partner_contact_address_default.py
  partner_contact_address_default/views/res_partner_views.xml
  partner_contact_age_range/__manifest__.py
Labels: 13.0

#695 Syncing from upstream OCA/partner-contact (14.0)
  partner_address_street3/i18n/it.po
  partner_identification/i18n/it.po
Labels: 14.0

#698 Syncing from upstream OCA/partner-contact (12.0)
  README.md
  partner_address_version/README.rst
  partner_address_version/__init__.py
  partner_address_version/__manifest__.py
  partner_address_version/i18n/partner_address_version.pot
  partner_address_version/models/__init__.py
  partner_address_version/models/res_partner.py
  partner_address_version/readme/CONTRIBUTORS.rst
  partner_address_version/readme/DESCRIPTION.rst
  partner_address_version/static/description/icon.png
  partner_address_version/static/description/index.html
  partner_address_version/tests/__init__.py
  partner_address_version/tests/test_address_version.py
  partner_address_version/wizards/__init__.py
  partner_address_version/wizards/base_partner_merge.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/partner_address_version/odoo/addons/partner_address_version
  setup/partner_address_version/setup.py
Labels: 12.0

#699 Syncing from upstream OCA/partner-contact (14.0)
  README.md
  partner_stage/README.rst
  partner_stage/__init__.py
  partner_stage/__manifest__.py
  partner_stage/data/partner_stage_data.xml
  partner_stage/i18n/partner_stage.pot
  partner_stage/init_hook.py
  partner_stage/migrations/14.0.2.0.0/post-migration.py
  partner_stage/migrations/14.0.2.0.0/pre-migrate.py
  partner_stage/models/__init__.py
  partner_stage/models/res_partner.py
  partner_stage/models/res_partner_stage.py
  partner_stage/readme/CONFIGURATION.rst
  partner_stage/readme/CONTRIBUTORS.rst
  partner_stage/readme/DESCRIPTION.rst
  partner_stage/readme/USAGE.rst
  partner_stage/security/ir.model.access.csv
  partner_stage/static/description/icon.png
  partner_stage/static/description/index.html
  partner_stage/tests/__init__.py
  partner_stage/tests/test_partner_stage.py
  partner_stage/views/res_partner_stage_views.xml
  partner_stage/views/res_partner_views.xml
  partner_tier_validation/i18n/partner_tier_validation.pot
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/partner_stage/odoo/addons/partner_stage
  setup/partner_stage/setup.py
Labels: 14.0

#701 Syncing from upstream OCA/partner-contact (12.0)
  README.md
  partner_contact_address_default/__manifest__.py
  partner_contact_address_default/i18n/es.po
  partner_contact_address_default/i18n/it.po
  partner_contact_address_default/i18n/partner_contact_address_default.pot
  partner_contact_address_default/i18n/pt.po
  partner_contact_address_default/models/__init__.py
  partner_contact_address_default/models/res_config_settings.py
  partner_contact_address_default/security/res_groups_security.xml
  partner_contact_address_default/views/res_config_settings_views.xml
  partner_contact_address_default/views/res_partner_views.xml
Labels: 12.0

#703 Syncing from upstream OCA/partner-contact (14.0)
  README.md
  partner_stage/i18n/partner_stage.pot
  partner_tier_validation/README.rst
  partner_tier_validation/__init__.py
  partner_tier_validation/__manifest__.py
  partner_tier_validation/data/tier_definition.xml
  partner_tier_validation/hooks.py
  partner_tier_validation/i18n/partner_tier_validation.pot
  partner_tier_validation/models/res_partner.py
  partner_tier_validation/static/description/index.html
  partner_tier_validation/tests/test_tier_validation.py
  partner_tier_validation/views/res_partner_view.xml
Labels: 14.0

#705 Syncing from upstream OCA/partner-contact (14.0)
  README.md
  partner_identification_gln/__manifest__.py
  requirements.txt
Labels: 14.0
