Repository brain-tec/partner-contact, pull requests merged in 2022-09, with the labels that each got.

#787 Syncing from upstream OCA/partner-contact (14.0)
  README.md
  partner_category_security/__init__.py
  partner_category_security/__manifest__.py
  partner_category_security/i18n/es.po
  partner_category_security/i18n/partner_category_security.pot
  partner_category_security/models/__init__.py
  partner_category_security/models/res_partner.py
  partner_category_security/security/ir.model.access.csv
  partner_category_security/tests/test_partner_category_security.py
  partner_category_security/views/res_partner_view.xml
Labels: 14.0

#789 Syncing from upstream OCA/partner-contact (14.0)
  README.md
  partner_email_duplicate_warn/README.rst
  partner_email_duplicate_warn/__init__.py
  partner_email_duplicate_warn/__manifest__.py
  partner_email_duplicate_warn/i18n/partner_email_duplicate_warn.pot
  partner_email_duplicate_warn/models/__init__.py
  partner_email_duplicate_warn/models/res_partner.py
  partner_email_duplicate_warn/readme/CONFIGURE.rst
  partner_email_duplicate_warn/readme/CONTRIBUTORS.rst
  partner_email_duplicate_warn/readme/DESCRIPTION.rst
  partner_email_duplicate_warn/readme/USAGE.rst
  partner_email_duplicate_warn/static/description/icon.png
  partner_email_duplicate_warn/static/description/index.html
  partner_email_duplicate_warn/static/description/partner_warn_banner.png
  partner_email_duplicate_warn/tests/__init__.py
  partner_email_duplicate_warn/tests/test_email_duplicate.py
  partner_email_duplicate_warn/views/res_partner.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/partner_email_duplicate_warn/odoo/addons/partner_email_duplicate_warn
  setup/partner_email_duplicate_warn/setup.py
Labels: 14.0

#791 Syncing from upstream OCA/partner-contact (14.0)
  base_location/i18n/fr.po
  partner_address_street3/i18n/de.po
  partner_address_street3/i18n/fr.po
Labels: 14.0

#793 [t131889][15.0] [MIG] partner tier validation
  partner_tier_validation/README.rst
  partner_tier_validation/__init__.py
  partner_tier_validation/__manifest__.py
  partner_tier_validation/data/tier_definition.xml
  partner_tier_validation/i18n/partner_tier_validation.pot
  partner_tier_validation/models/__init__.py
  partner_tier_validation/models/res_partner.py
  partner_tier_validation/models/tier_definition.py
  partner_tier_validation/readme/CONFIGURATION.rst
  partner_tier_validation/readme/CONTRIBUTORS.rst
  partner_tier_validation/readme/DESCRIPTION.rst
  partner_tier_validation/readme/INSTALL.rst
  partner_tier_validation/readme/USAGE.rst
  partner_tier_validation/static/description/icon.png
  partner_tier_validation/static/description/index.html
  partner_tier_validation/test-requirements.txt
  partner_tier_validation/tests/__init__.py
  partner_tier_validation/tests/test_tier_validation.py
  partner_tier_validation/views/res_partner_view.xml
  setup/partner_tier_validation/odoo/addons/partner_tier_validation
  setup/partner_tier_validation/setup.py
Labels: 15.0.project_gr_646.t131889

#794 [t131889] [MIG] partner_stage and partner_tier_validation
  README.md
  partner_stage/README.rst
  partner_stage/__init__.py
  partner_stage/__manifest__.py
  partner_stage/data/partner_stage_data.xml
  partner_stage/i18n/partner_stage.pot
  partner_stage/i18n/pt.po
  partner_stage/init_hook.py
  partner_stage/models/__init__.py
  partner_stage/models/res_partner.py
  partner_stage/models/res_partner_stage.py
  partner_stage/readme/CONFIGURATION.rst
  partner_stage/readme/CONTRIBUTORS.rst
  partner_stage/readme/DESCRIPTION.rst
  partner_stage/readme/USAGE.rst
  partner_stage/security/ir.model.access.csv
  partner_stage/static/description/icon.png
  partner_stage/static/description/index.html
  partner_stage/tests/__init__.py
  partner_stage/tests/test_partner_stage.py
  partner_stage/views/res_partner_stage_views.xml
  partner_stage/views/res_partner_views.xml
  partner_tier_validation/README.rst
  partner_tier_validation/__init__.py
  partner_tier_validation/__manifest__.py
  partner_tier_validation/data/tier_definition.xml
  partner_tier_validation/i18n/partner_tier_validation.pot
  partner_tier_validation/models/__init__.py
  partner_tier_validation/models/res_partner.py
  partner_tier_validation/models/tier_definition.py
  partner_tier_validation/readme/CONFIGURATION.rst
  partner_tier_validation/readme/CONTRIBUTORS.rst
  partner_tier_validation/readme/DESCRIPTION.rst
  partner_tier_validation/readme/INSTALL.rst
  partner_tier_validation/readme/USAGE.rst
  partner_tier_validation/static/description/icon.png
  partner_tier_validation/static/description/index.html
  partner_tier_validation/test-requirements.txt
  partner_tier_validation/tests/__init__.py
  partner_tier_validation/tests/test_tier_validation.py
  partner_tier_validation/views/res_partner_view.xml
  setup/partner_stage/odoo/addons/partner_stage
  setup/partner_stage/setup.py
  setup/partner_tier_validation/odoo/addons/partner_tier_validation
  setup/partner_tier_validation/setup.py
Labels: 15.0.project_gr_646

#795 Syncing from upstream OCA/partner-contact (14.0)
  partner_employee_quantity/i18n/fr.po
Labels: 14.0

#796 Syncing from upstream OCA/partner-contact (14.0)
  partner_contact_in_several_companies/i18n/fr.po
  partner_contact_in_several_companies/i18n/fr_CH.po
  partner_contact_in_several_companies/i18n/fr_FR.po
Labels: 14.0

#797 Syncing from upstream OCA/partner-contact (14.0)
  partner_title_order/i18n/fr.po
Labels: 14.0

#798 Syncing from upstream OCA/partner-contact (14.0)
  partner_address_street3/i18n/fr.po
  partner_data_vies_populator/i18n/fr.po
  partner_deduplicate_acl/i18n/fr.po
  partner_deduplicate_by_ref/i18n/fr.po
  partner_deduplicate_by_website/i18n/fr.po
  partner_mobile_duplicate_warn/i18n/fr.po
  partner_mobile_duplicate_warn/i18n/fr_BE.po
  partner_mobile_duplicate_warn/i18n/fr_CH.po
Labels: 14.0

#799 Syncing from upstream OCA/partner-contact (15.0)
  README.md
  base_partner_company_group/__manifest__.py
  base_partner_company_group/i18n/base_partner_company_group.pot
  base_partner_company_group/models/res_partner.py
  base_partner_company_group/tests/test_base_partner_company_group.py
  base_partner_company_group/views/contact_view.xml
Labels: 15.0
