Repository brain-tec/partner-contact, pull requests merged in 2022-01, with the labels that each got.

#669 Syncing from upstream OCA/partner-contact (12.0)
  base_location/migrations/12.0.1.0.0/post-migration.py
Labels: 12.0

#670 Syncing from upstream OCA/partner-contact (14.0)
  README.md
  animal_owner/__manifest__.py
  animal_owner/models/animal.py
Labels: 14.0

#672 Merging 15.0 into 15.0.project_MI_465
  base_location/README.rst
  base_location/__manifest__.py
  base_location/static/description/index.html
  base_location_geonames_import/README.rst
  base_location_geonames_import/__manifest__.py
  base_location_geonames_import/static/description/index.html
Labels: 15.0.project_mi_465

#673 Syncing from upstream OCA/partner-contact (14.0)
  partner_contact_access_link/i18n/it.po
Labels: 14.0

#674 Syncing from upstream OCA/partner-contact (15.0)
  README.md
  partner_contact_access_link/README.rst
  partner_contact_access_link/__init__.py
  partner_contact_access_link/__manifest__.py
  partner_contact_access_link/i18n/partner_contact_access_link.pot
  partner_contact_access_link/models/__init__.py
  partner_contact_access_link/models/res_partner.py
  partner_contact_access_link/readme/CONTRIBUTORS.rst
  partner_contact_access_link/readme/DESCRIPTION.rst
  partner_contact_access_link/readme/USAGE.rst
  partner_contact_access_link/static/description/full-form.gif
  partner_contact_access_link/static/description/icon.png
  partner_contact_access_link/static/description/index.html
  partner_contact_access_link/tests/__init__.py
  partner_contact_access_link/tests/test_partner_contact_access_link.py
  partner_contact_access_link/views/res_partner_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/partner_contact_access_link/odoo/addons/partner_contact_access_link
  setup/partner_contact_access_link/setup.py
Labels: 15.0

#675 Syncing from upstream OCA/partner-contact (12.0)
  partner_affiliate/i18n/fr.po
Labels: 12.0

#676 Syncing from upstream OCA/partner-contact (13.0)
  partner_affiliate/i18n/fr.po
Labels: 13.0

#677 Syncing from upstream OCA/partner-contact (14.0)
  animal/i18n/fr.po
  animal_owner/i18n/fr.po
Labels: 14.0

#678 Syncing from upstream OCA/partner-contact (13.0)
  README.md
  partner_contact_address_default/__manifest__.py
  partner_contact_address_default/models/res_partner.py
  partner_contact_address_default/tests/test_partner_contact_address_default.py
Labels: 13.0

#679 Syncing from upstream OCA/partner-contact (14.0)
  README.md
  partner_contact_address_default/__manifest__.py
  partner_contact_address_default/models/res_partner.py
  partner_contact_address_default/tests/test_partner_contact_address_default.py
Labels: 14.0

#680 Syncing from upstream OCA/partner-contact (14.0)
  partner_company_type/i18n/sv.po
  partner_firstname/i18n/sv.po
  partner_phone_secondary/i18n/sv.po
Labels: 14.0
