Repository brain-tec/partner-contact, pull requests merged in 2022-04, with the labels that each got.

#726 Syncing from upstream OCA/partner-contact (14.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  README.md
  base_location_nuts/tests/test_base_location_nuts.py
  partner_address_street3/hooks.py
  partner_address_version/tests/test_address_version.py
  partner_contact_department/tests/test_recursion.py
  partner_email_check/tests/test_partner_email_check.py
  partner_firstname/tests/test_copy.py
  partner_identification/tests/test_partner_identification.py
  partner_identification/tests/test_res_partner.py
  partner_industry_secondary/models/res_partner_industry.py
  partner_pricelist_search/tests/test_partner_pricelist_search.py
  partner_second_lastname/models/res_partner.py
Labels: 14.0

#727 Syncing from upstream OCA/partner-contact (15.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .t2d.yml
  README.md
  partner_firstname/tests/test_copy.py
Labels: 15.0

#728 Syncing from upstream OCA/partner-contact (15.0)
  .copier-answers.yml
  README.md
  base_location_geonames_import/__manifest__.py
  base_location_geonames_import/wizard/geonames_import.py
  base_partner_company_group/README.rst
  base_partner_company_group/__init__.py
  base_partner_company_group/__manifest__.py
  base_partner_company_group/i18n/base_partner_company_group.pot
  base_partner_company_group/i18n/es.po
  base_partner_company_group/i18n/partner_company_group.pot
  base_partner_company_group/i18n/zh_CN.po
  base_partner_company_group/models/__init__.py
  base_partner_company_group/models/res_partner.py
  base_partner_company_group/readme/CONTRIBUTORS.rst
  base_partner_company_group/readme/DESCRIPTION.rst
  base_partner_company_group/static/description/icon.png
  base_partner_company_group/static/description/index.html
  base_partner_company_group/tests/__init__.py
  base_partner_company_group/tests/test_base_partner_company_group.py
  base_partner_company_group/views/contact_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/base_partner_company_group/odoo/addons/base_partner_company_group
  setup/base_partner_company_group/setup.py
Labels: 15.0

#729 Syncing from upstream OCA/partner-contact (15.0)
  partner_contact_access_link/i18n/ca.po
  partner_contact_birthdate/i18n/ca.po
  partner_contact_personal_information_page/i18n/ca.po
  partner_fax/i18n/ca.po
  partner_firstname/i18n/ca.po
Labels: 15.0

#731 Syncing from upstream OCA/partner-contact (13.0)
  README.md
  partner_company_group/README.rst
  partner_company_group/__manifest__.py
  partner_company_group/i18n/ca.po
  partner_company_group/i18n/ca_ES.po
  partner_company_group/i18n/es.po
  partner_company_group/i18n/partner_company_group.pot
  partner_company_group/i18n/zh_CN.po
  partner_company_group/models/res_partner.py
  partner_company_group/readme/CONTRIBUTORS.rst
  partner_company_group/static/description/index.html
  partner_company_group/tests/__init__.py
  partner_company_group/tests/test_partner_company_group.py
  partner_company_group/views/contact_view.xml
Labels: 13.0

#732 Syncing from upstream OCA/partner-contact (12.0)
  partner_multi_name/i18n/es CO.po
  partner_multi_name/i18n/es.po
Labels: 12.0

#733 Updating from latest OCA 15.0
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .t2d.yml
  README.md
  base_location_geonames_import/__manifest__.py
  base_location_geonames_import/wizard/geonames_import.py
  base_partner_company_group/README.rst
  base_partner_company_group/__init__.py
  base_partner_company_group/__manifest__.py
  base_partner_company_group/i18n/base_partner_company_group.pot
  base_partner_company_group/i18n/es.po
  base_partner_company_group/i18n/partner_company_group.pot
  base_partner_company_group/i18n/zh_CN.po
  base_partner_company_group/models/__init__.py
  base_partner_company_group/models/res_partner.py
  base_partner_company_group/readme/CONTRIBUTORS.rst
  base_partner_company_group/readme/DESCRIPTION.rst
  base_partner_company_group/static/description/icon.png
  base_partner_company_group/static/description/index.html
  base_partner_company_group/tests/__init__.py
  base_partner_company_group/tests/test_base_partner_company_group.py
  base_partner_company_group/views/contact_view.xml
  partner_contact_access_link/i18n/ca.po
  partner_contact_birthdate/i18n/ca.po
  partner_contact_personal_information_page/i18n/ca.po
  partner_fax/i18n/ca.po
  partner_firstname/i18n/ca.po
  partner_firstname/tests/test_copy.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/base_partner_company_group/odoo/addons/base_partner_company_group
  setup/base_partner_company_group/setup.py
Labels: 15.0.project_mi_465

#734 Syncing from upstream OCA/partner-contact (13.0)
  README.md
  partner_external_map/__manifest__.py
  partner_external_map/views/res_partner_view.xml
Labels: 13.0

#735 Syncing from upstream OCA/partner-contact (13.0)
  partner_firstname/i18n/fr.po
Labels: 13.0

#736 Syncing from upstream OCA/partner-contact (15.0)
  base_location_geonames_import/i18n/ca.po
  partner_industry_secondary/i18n/ca.po
Labels: 15.0

#737 Syncing from upstream OCA/partner-contact (13.0)
  README.md
  partner_pricelist_tracking/README.rst
  partner_pricelist_tracking/__init__.py
  partner_pricelist_tracking/__manifest__.py
  partner_pricelist_tracking/i18n/partner_pricelist_tracking.pot
  partner_pricelist_tracking/models/__init__.py
  partner_pricelist_tracking/models/res_partner.py
  partner_pricelist_tracking/readme/CONTRIBUTORS.rst
  partner_pricelist_tracking/readme/DESCRIPTION.rst
  partner_pricelist_tracking/readme/ROADMAP.rst
  partner_pricelist_tracking/static/description/icon.png
  partner_pricelist_tracking/static/description/index.html
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/partner_pricelist_tracking/odoo/addons/partner_pricelist_tracking
  setup/partner_pricelist_tracking/setup.py
Labels: 13.0

#738 Syncing from upstream OCA/partner-contact (14.0)
  partner_manual_rank/i18n/pt.po
Labels: 14.0

#739 Updating from latest OCA 15.0
  base_location_geonames_import/i18n/ca.po
  partner_industry_secondary/i18n/ca.po
Labels: 15.0.project_mi_465

#740 Syncing from upstream OCA/partner-contact (15.0)
  animal/i18n/ca.po
  base_country_state_translatable/i18n/ca.po
  base_location/i18n/ca.po
  base_location_geonames_import/i18n/ca.po
  base_partner_company_group/i18n/ca.po
  base_partner_sequence/i18n/ca.po
  partner_affiliate/i18n/ca.po
  partner_contact_age_range/i18n/ca.po
  partner_firstname/i18n/ca.po
  partner_phone_secondary/i18n/ca.po
  partner_ref_unique/i18n/ca.po
Labels: 15.0

#741 Syncing from upstream OCA/partner-contact (12.0)
  README.md
  partner_contact_address_default/README.rst
  partner_contact_address_default/__manifest__.py
  partner_contact_address_default/readme/CONTRIBUTORS.rst
  partner_contact_address_default/static/description/index.html
  partner_contact_address_default/views/res_partner_views.xml
Labels: 12.0

#742 Syncing from upstream OCA/partner-contact (14.0)
  partner_manual_rank/i18n/es.po
Labels: 14.0

#743 Syncing from upstream OCA/partner-contact (13.0)
  README.md
  partner_company_group/__manifest__.py
  partner_company_group/models/res_partner.py
Labels: 13.0

#744 Syncing from upstream OCA/partner-contact (14.0)
  README.md
  partner_company_group/README.rst
  partner_company_group/__manifest__.py
  partner_company_group/i18n/ca.po
  partner_company_group/i18n/es.po
  partner_company_group/i18n/partner_company_group.pot
  partner_company_group/i18n/zh_CN.po
  partner_company_group/models/res_partner.py
  partner_company_group/readme/CONTRIBUTORS.rst
  partner_company_group/static/description/index.html
  partner_company_group/tests/test_partner_company_group.py
  partner_company_group/views/contact_view.xml
  partner_tier_validation/i18n/partner_tier_validation.pot
Labels: 14.0
