Repository brain-tec/partner-contact, pull requests merged in 2023-01, with the labels that each got.

#851 Syncing from upstream OCA/partner-contact (8.0)
  base_partner_merge/i18n/it.po
  partner_capital/i18n/it.po
  partner_contact_job_position/i18n/it.po
  partner_employee_quantity/i18n/it.po
  partner_external_maps/i18n/it.po
  partner_financial_risk/i18n/it.po
  partner_identification/i18n/it.po
  partner_relations/i18n/it.po
  passport/i18n/it.po
Labels: 8.0

#852 Syncing from upstream OCA/partner-contact (9.0)
  partner_changeset/i18n/it.po
  partner_contact_job_position/i18n/it.po
  partner_financial_risk/i18n/it.po
  partner_multi_relation/i18n/it.po
Labels: 9.0

#853 Syncing from upstream OCA/partner-contact (10.0)
  partner_financial_risk/i18n/it.po
Labels: 10.0

#854 Syncing from upstream OCA/partner-contact (12.0)
  base_location/i18n/it.po
  partner_identification/i18n/it.po
  partner_multi_relation_tabs/i18n/it.po
Labels: 12.0

#855 Syncing from upstream OCA/partner-contact (13.0)
  base_location/i18n/it.po
  partner_identification/i18n/it.po
Labels: 13.0

#856 Syncing from upstream OCA/partner-contact (14.0)
  base_location/i18n/it.po
  partner_contact_address_default/i18n/it.po
  partner_identification/i18n/it.po
Labels: 14.0

#857 Syncing from upstream OCA/partner-contact (15.0)
  base_location/i18n/it.po
Labels: 15.0

#858 Syncing from upstream OCA/partner-contact (16.0)
  base_location/i18n/it.po
  partner_identification/i18n/it.po
Labels: 16.0

#860 Syncing from upstream OCA/partner-contact (16.0)
  base_location/i18n/hr.po
  partner_accreditation/i18n/hr.po
  partner_contact_birthdate/i18n/hr.po
  partner_contact_gender/i18n/hr.po
  partner_contact_lang/i18n/hr.po
  partner_identification/i18n/it.po
  partner_vat_unique/i18n/hr.po
Labels: 16.0

#861 Syncing from upstream OCA/partner-contact (16.0)
  partner_company_type/i18n/hr.po
  partner_firstname/i18n/hr.po
  partner_identification/i18n/hr.po
Labels: 16.0

#862 Syncing from upstream OCA/partner-contact (14.0)
  partner_pricelist_search/i18n/fr.po
Labels: 14.0

#863 Syncing from upstream OCA/partner-contact (13.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  README.md
  partner_address_street3/i18n/en.po
  partner_company_group/__manifest__.py
  partner_company_group/models/res_partner.py
  partner_contact_personal_information_page/i18n/en.po
  partner_data_vies_populator/README.rst
  partner_data_vies_populator/__manifest__.py
  partner_data_vies_populator/readme/DESCRIPTION.rst
  partner_data_vies_populator/static/description/index.html
  partner_data_vies_populator/tests/test_partner_data_vies_populator.py
  partner_email_check/__manifest__.py
  requirements.txt
Labels: 13.0

#864 Syncing from upstream OCA/partner-contact (12.0)
  partner_vat_unique/i18n/it.po
Labels: 12.0

#867 Syncing from upstream OCA/partner-contact (15.0)
  README.md
  partner_deduplicate_acl/__manifest__.py
  partner_deduplicate_acl/views/base_partner_merge_view.xml
Labels: 15.0

#868 Syncing from upstream OCA/partner-contact (13.0)
  README.md
  base_partner_sequence/__manifest__.py
  base_partner_sequence/models/partner.py
Labels: 13.0

#870 Syncing from upstream OCA/partner-contact (9.0)
  partner_stock_risk/i18n/it.po
Labels: 9.0

#871 Syncing from upstream OCA/partner-contact (10.0)
  partner_stock_risk/i18n/it.po
Labels: 10.0

#872 Syncing from upstream OCA/partner-contact (14.0)
  base_location/i18n/it.po
  partner_industry_secondary/i18n/pt.po
Labels: 14.0

#873 Syncing from upstream OCA/partner-contact (14.0)
  README.md
  base_partner_sequence/__manifest__.py
  base_partner_sequence/models/partner.py
Labels: 14.0

#874 16.0 mig partner contact address default
  partner_contact_address_default/README.rst
  partner_contact_address_default/__init__.py
  partner_contact_address_default/__manifest__.py
  partner_contact_address_default/i18n/es.po
  partner_contact_address_default/i18n/fr.po
  partner_contact_address_default/i18n/fr_FR.po
  partner_contact_address_default/i18n/partner_contact_address_default.pot
  partner_contact_address_default/i18n/pt.po
  partner_contact_address_default/models/__init__.py
  partner_contact_address_default/models/res_partner.py
  partner_contact_address_default/readme/CONTRIBUTORS.rst
  partner_contact_address_default/readme/DESCRIPTION.rst
  partner_contact_address_default/readme/USAGE.rst
  partner_contact_address_default/static/description/icon.png
  partner_contact_address_default/static/description/index.html
  partner_contact_address_default/tests/__init__.py
  partner_contact_address_default/tests/test_partner_contact_address_default.py
  partner_contact_address_default/views/res_partner_views.xml
  setup/partner_contact_address_default/odoo/addons/partner_contact_address_default
  setup/partner_contact_address_default/setup.py
Labels: 16.0.project_ak_662

#876 Syncing from upstream OCA/partner-contact (14.0)
  partner_contact_access_link/i18n/it.po
Labels: 14.0

#877 Syncing from upstream OCA/partner-contact (16.0)
  partner_accreditation/i18n/fr.po
Labels: 16.0

#879 Syncing from upstream OCA/partner-contact (15.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  README.md
  partner_company_default/README.rst
  partner_company_default/__init__.py
  partner_company_default/__manifest__.py
  partner_company_default/i18n/partner_company_default.pot
  partner_company_default/models/__init__.py
  partner_company_default/models/res_partner.py
  partner_company_default/readme/DESCRIPTION.rst
  partner_company_default/static/description/icon.png
  partner_company_default/static/description/index.html
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/partner_company_default/odoo/addons/partner_company_default
  setup/partner_company_default/setup.py
Labels: 15.0

#880 Syncing from upstream OCA/partner-contact (16.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: 16.0
