Repository brain-tec/partner-contact, pull requests merged in 2023-02, with the labels that each got.

#881 Syncing from upstream OCA/partner-contact (16.0)
  base_country_state_translatable/i18n/hr.po
  base_location/i18n/hr.po
  base_location_geonames_import/i18n/hr.po
  partner_accreditation/i18n/hr.po
  partner_address_street3/i18n/hr.po
  partner_affiliate/i18n/hr.po
  partner_company_type/i18n/hr.po
  partner_contact_job_position/i18n/hr.po
  partner_contact_nationality/i18n/hr.po
  partner_external_map/i18n/hr.po
  partner_multi_relation/i18n/hr.po
  partner_second_lastname/i18n/hr.po
  partner_vat_unique/i18n/de.po
  partner_vat_unique/i18n/es.po
  partner_vat_unique/i18n/hr.po
  partner_vat_unique/i18n/it.po
  partner_vat_unique/i18n/partner_vat_unique.pot
  partner_vat_unique/i18n/pt.po
Labels: 16.0

#882 Syncing from upstream OCA/partner-contact (10.0)
  partner_sale_risk/i18n/it.po
Labels: 10.0

#883 Syncing from upstream OCA/partner-contact (12.0)
  partner_company_group/i18n/it.po
  partner_deduplicate_by_website/i18n/it.po
Labels: 12.0

#884 Syncing from upstream OCA/partner-contact (13.0)
  partner_deduplicate_by_website/i18n/it.po
Labels: 13.0

#885 Syncing from upstream OCA/partner-contact (14.0)
  partner_contact_address_default/i18n/de.po
  partner_deduplicate_by_website/i18n/it.po
Labels: 14.0

#886 Syncing from upstream OCA/partner-contact (16.0)
  partner_identification/i18n/hr.po
Labels: 16.0

#887 Syncing from upstream OCA/partner-contact (12.0)
  partner_company_group/i18n/it.po
Labels: 12.0

#888 Syncing from upstream OCA/partner-contact (14.0)
  README.md
  partner_data_vies_populator/README.rst
  partner_data_vies_populator/__manifest__.py
  partner_data_vies_populator/readme/DESCRIPTION.rst
  partner_data_vies_populator/readme/INSTALL.rst
  partner_data_vies_populator/static/description/index.html
Labels: 14.0

#889 Syncing from upstream OCA/partner-contact (15.0)
  base_partner_company_group/i18n/it.po
Labels: 15.0

#891 Syncing from upstream OCA/partner-contact (16.0)
  README.md
  base_location_geonames_import/i18n/fr.po
  partner_manual_rank/README.rst
  partner_manual_rank/__init__.py
  partner_manual_rank/__manifest__.py
  partner_manual_rank/i18n/es.po
  partner_manual_rank/i18n/it.po
  partner_manual_rank/i18n/partner_manual_rank.pot
  partner_manual_rank/i18n/pt.po
  partner_manual_rank/models/__init__.py
  partner_manual_rank/models/res_partner.py
  partner_manual_rank/readme/CONTRIBUTORS.rst
  partner_manual_rank/readme/CREDITS.rst
  partner_manual_rank/readme/DESCRIPTION.rst
  partner_manual_rank/static/description/icon.png
  partner_manual_rank/static/description/index.html
  partner_manual_rank/tests/__init__.py
  partner_manual_rank/tests/test_res_partner.py
  partner_manual_rank/views/res_partner.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/partner_manual_rank/odoo/addons/partner_manual_rank
  setup/partner_manual_rank/setup.py
Labels: 16.0

#892 Migration partner_fax v16
  partner_fax/README.rst
  partner_fax/__init__.py
  partner_fax/__manifest__.py
  partner_fax/i18n/ca.po
  partner_fax/i18n/de.po
  partner_fax/i18n/es.po
  partner_fax/i18n/fr.po
  partner_fax/i18n/he.po
  partner_fax/i18n/hr_HR.po
  partner_fax/i18n/it.po
  partner_fax/i18n/nl.po
  partner_fax/i18n/partner_fax.pot
  partner_fax/i18n/pt_BR.po
  partner_fax/i18n/sl.po
  partner_fax/i18n/zh_CN.po
  partner_fax/models/__init__.py
  partner_fax/models/res_partner.py
  partner_fax/readme/CONTRIBUTORS.rst
  partner_fax/readme/DESCRIPTION.rst
  partner_fax/readme/USAGE.rst
  partner_fax/static/description/icon.png
  partner_fax/static/description/index.html
  partner_fax/views/res_partner.xml
  setup/partner_fax/odoo/addons/partner_fax
  setup/partner_fax/setup.py
Labels: 16.0.project_gu_673

#893 Syncing from upstream OCA/partner-contact (13.0)
  README.md
  base_location/__manifest__.py
  base_location/models/res_partner.py
Labels: 13.0

#894 Syncing from upstream OCA/partner-contact (16.0)
  README.md
  partner_email_duplicate_warn/README.rst
  partner_email_duplicate_warn/__init__.py
  partner_email_duplicate_warn/__manifest__.py
  partner_email_duplicate_warn/i18n/partner_email_duplicate_warn.pot
  partner_email_duplicate_warn/models/__init__.py
  partner_email_duplicate_warn/models/res_partner.py
  partner_email_duplicate_warn/readme/CONFIGURE.rst
  partner_email_duplicate_warn/readme/CONTRIBUTORS.rst
  partner_email_duplicate_warn/readme/DESCRIPTION.rst
  partner_email_duplicate_warn/readme/ROADMAP.rst
  partner_email_duplicate_warn/readme/USAGE.rst
  partner_email_duplicate_warn/static/description/icon.png
  partner_email_duplicate_warn/static/description/index.html
  partner_email_duplicate_warn/static/description/partner_warn_banner.png
  partner_email_duplicate_warn/tests/__init__.py
  partner_email_duplicate_warn/tests/test_email_duplicate.py
  partner_email_duplicate_warn/views/res_partner.xml
  partner_fax/README.rst
  partner_fax/__init__.py
  partner_fax/__manifest__.py
  partner_fax/i18n/ca.po
  partner_fax/i18n/de.po
  partner_fax/i18n/es.po
  partner_fax/i18n/fr.po
  partner_fax/i18n/he.po
  partner_fax/i18n/hr_HR.po
  partner_fax/i18n/it.po
  partner_fax/i18n/nl.po
  partner_fax/i18n/partner_fax.pot
  partner_fax/i18n/pt_BR.po
  partner_fax/i18n/sl.po
  partner_fax/i18n/zh_CN.po
  partner_fax/models/__init__.py
  partner_fax/models/res_partner.py
  partner_fax/readme/CONTRIBUTORS.rst
  partner_fax/readme/DESCRIPTION.rst
  partner_fax/readme/USAGE.rst
  partner_fax/static/description/icon.png
  partner_fax/static/description/index.html
  partner_fax/views/res_partner.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/partner_email_duplicate_warn/odoo/addons/partner_email_duplicate_warn
  setup/partner_email_duplicate_warn/setup.py
  setup/partner_fax/odoo/addons/partner_fax
  setup/partner_fax/setup.py
Labels: 16.0

#895 Syncing from upstream OCA/partner-contact (15.0)
  README.md
  partner_email_check/README.rst
  partner_email_check/__init__.py
  partner_email_check/__manifest__.py
  partner_email_check/demo/res_company_demo.xml
  partner_email_check/i18n/fr.po
  partner_email_check/i18n/it.po
  partner_email_check/i18n/partner_email_check.pot
  partner_email_check/models/__init__.py
  partner_email_check/models/res_company.py
  partner_email_check/models/res_config_settings.py
  partner_email_check/models/res_partner.py
  partner_email_check/readme/CONFIGURE.rst
  partner_email_check/readme/CONTRIBUTORS.rst
  partner_email_check/readme/DESCRIPTION.rst
  partner_email_check/readme/USAGE.rst
  partner_email_check/static/description/icon.png
  partner_email_check/static/description/index.html
  partner_email_check/tests/__init__.py
  partner_email_check/tests/test_partner_email_check.py
  partner_email_check/views/base_config_view.xml
  requirements.txt
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/partner_email_check/odoo/addons/partner_email_check
  setup/partner_email_check/setup.py
Labels: 15.0

#896 Syncing from upstream OCA/partner-contact (16.0)
  partner_accreditation/i18n/hr.po
  partner_contact_access_link/i18n/hr.po
  partner_contact_personal_information_page/i18n/hr.po
Labels: 16.0

#897 Syncing from upstream OCA/partner-contact (9.0)
  partner_sale_risk/i18n/it.po
Labels: 9.0

#898 Syncing from upstream OCA/partner-contact (16.0)
  README.md
  base_location/__manifest__.py
  base_location/tests/test_base_location.py
Labels: 16.0

#899 Syncing from upstream OCA/partner-contact (16.0)
  README.md
  partner_address_two_lines/README.rst
  partner_address_two_lines/__init__.py
  partner_address_two_lines/__manifest__.py
  partner_address_two_lines/i18n/partner_address_two_lines.pot
  partner_address_two_lines/models/__init__.py
  partner_address_two_lines/models/ir_actions_report.py
  partner_address_two_lines/models/res_partner.py
  partner_address_two_lines/readme/CONTRIBUTORS.rst
  partner_address_two_lines/readme/DESCRIPTION.rst
  partner_address_two_lines/static/description/icon.png
  partner_address_two_lines/static/description/index.html
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/partner_address_two_lines/odoo/addons/partner_address_two_lines
  setup/partner_address_two_lines/setup.py
Labels: 16.0

#900 Syncing from upstream OCA/partner-contact (13.0)
  README.md
  partner_country_lang/README.rst
  partner_country_lang/__init__.py
  partner_country_lang/__manifest__.py
  partner_country_lang/i18n/es.po
  partner_country_lang/i18n/partner_country_lang.pot
  partner_country_lang/models/__init__.py
  partner_country_lang/models/res_country.py
  partner_country_lang/models/res_partner.py
  partner_country_lang/readme/CONFIGURE.rst
  partner_country_lang/readme/CONTRIBUTORS.rst
  partner_country_lang/readme/DESCRIPTION.rst
  partner_country_lang/readme/USAGE.rst
  partner_country_lang/static/description/icon.png
  partner_country_lang/static/description/index.html
  partner_country_lang/tests/__init__.py
  partner_country_lang/tests/test_partner_country_lang.py
  partner_country_lang/views/res_country_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/partner_country_lang/odoo/addons/partner_country_lang
  setup/partner_country_lang/setup.py
Labels: 13.0

#901 Syncing from upstream OCA/partner-contact (15.0)
  README.md
  partner_country_lang/README.rst
  partner_country_lang/__init__.py
  partner_country_lang/__manifest__.py
  partner_country_lang/i18n/es.po
  partner_country_lang/i18n/partner_country_lang.pot
  partner_country_lang/models/__init__.py
  partner_country_lang/models/res_country.py
  partner_country_lang/models/res_partner.py
  partner_country_lang/readme/CONFIGURE.rst
  partner_country_lang/readme/CONTRIBUTORS.rst
  partner_country_lang/readme/DESCRIPTION.rst
  partner_country_lang/readme/USAGE.rst
  partner_country_lang/static/description/icon.png
  partner_country_lang/static/description/index.html
  partner_country_lang/tests/__init__.py
  partner_country_lang/tests/test_partner_country_lang.py
  partner_country_lang/views/res_country_view.xml
  partner_pricelist_tracking/README.rst
  partner_pricelist_tracking/__init__.py
  partner_pricelist_tracking/__manifest__.py
  partner_pricelist_tracking/i18n/partner_pricelist_tracking.pot
  partner_pricelist_tracking/models/__init__.py
  partner_pricelist_tracking/models/res_partner.py
  partner_pricelist_tracking/readme/CONFIGURE.rst
  partner_pricelist_tracking/readme/CONTRIBUTORS.rst
  partner_pricelist_tracking/readme/DESCRIPTION.rst
  partner_pricelist_tracking/readme/ROADMAP.rst
  partner_pricelist_tracking/static/description/icon.png
  partner_pricelist_tracking/static/description/index.html
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/partner_country_lang/odoo/addons/partner_country_lang
  setup/partner_country_lang/setup.py
  setup/partner_pricelist_tracking/odoo/addons/partner_pricelist_tracking
  setup/partner_pricelist_tracking/setup.py
Labels: 15.0
