Repository brain-tec/partner-contact, pull requests merged in 2024-11, with the labels that each got.

#1306 18.0 mig sale partner company group
  .oca/oca-port/blacklist/sale_partner_company_group.json
  sale_partner_company_group/README.rst
  sale_partner_company_group/__init__.py
  sale_partner_company_group/__manifest__.py
  sale_partner_company_group/hooks.py
  sale_partner_company_group/i18n/es.po
  sale_partner_company_group/i18n/it.po
  sale_partner_company_group/i18n/pt_BR.po
  sale_partner_company_group/i18n/sale_partner_company_group.pot
  sale_partner_company_group/i18n/zh_CN.po
  sale_partner_company_group/models/__init__.py
  sale_partner_company_group/models/res_partner.py
  sale_partner_company_group/models/sale_order.py
  sale_partner_company_group/pyproject.toml
  sale_partner_company_group/readme/CONTRIBUTORS.md
  sale_partner_company_group/readme/CREDITS.md
  sale_partner_company_group/readme/DESCRIPTION.md
  sale_partner_company_group/static/description/icon.png
  sale_partner_company_group/static/description/index.html
  sale_partner_company_group/tests/__init__.py
  sale_partner_company_group/tests/test_sale_partner_company_group.py
  sale_partner_company_group/views/sale_order_view.xml
Labels: 18.0.project_ca_772

#1309 Syncing from upstream OCA/partner-contact (17.0)
  README.md
  partner_display_name_line_break/README.rst
  partner_display_name_line_break/__manifest__.py
  partner_display_name_line_break/models/res_partner.py
  partner_display_name_line_break/static/description/index.html
  partner_display_name_line_break/tests/test_res_partner.py
Labels: 17.0

#1310 Syncing from upstream OCA/partner-contact (8.0)
  partner_financial_risk/i18n/it.po
Labels: 8.0

#1311 Syncing from upstream OCA/partner-contact (9.0)
  partner_financial_risk/i18n/it.po
Labels: 9.0

#1312 Syncing from upstream OCA/partner-contact (10.0)
  partner_financial_risk/i18n/it.po
Labels: 10.0

#1313 Syncing from upstream OCA/partner-contact (16.0)
  README.md
  partner_contact_access_link/README.rst
  partner_contact_access_link/__manifest__.py
  partner_contact_access_link/static/description/index.html
  partner_contact_access_link/views/res_partner_views.xml
Labels: 16.0

#1314 Syncing from upstream OCA/partner-contact (16.0)
  base_location_geonames_import/i18n/fr.po
  base_partner_sequence/i18n/fr.po
  partner_affiliate/i18n/fr.po
  partner_firstname/i18n/fr.po
  partner_identification_gln/i18n/fr.po
Labels: 16.0

#1315 18.0 mig partner contact role
  partner_contact_role/README.rst
  partner_contact_role/__init__.py
  partner_contact_role/__manifest__.py
  partner_contact_role/i18n/es.po
  partner_contact_role/i18n/fr.po
  partner_contact_role/i18n/it.po
  partner_contact_role/i18n/partner_contact_role.pot
  partner_contact_role/models/__init__.py
  partner_contact_role/models/res_partner.py
  partner_contact_role/pyproject.toml
  partner_contact_role/readme/CONFIGURE.md
  partner_contact_role/readme/CONTRIBUTORS.md
  partner_contact_role/readme/CREDITS.md
  partner_contact_role/readme/DESCRIPTION.md
  partner_contact_role/readme/USAGE.md
  partner_contact_role/security/ir.model.access.csv
  partner_contact_role/static/description/icon.png
  partner_contact_role/static/description/index.html
  partner_contact_role/views/res_partner.xml
  partner_contact_role/views/res_partner_role.xml
Labels: 18.0.project_ca_772

#1317 Syncing from upstream OCA/partner-contact (17.0)
  README.md
  partner_firstname/README.rst
  partner_firstname/__manifest__.py
  partner_firstname/static/description/index.html
  partner_firstname/views/res_partner.xml
Labels: 17.0

#1318 Syncing from upstream OCA/partner-contact (18.0)
  README.md
  partner_firstname/README.rst
  partner_firstname/__manifest__.py
  partner_firstname/static/description/index.html
  partner_firstname/views/res_partner.xml
Labels: 18.0
